title: Networks in Science of Science
description: "A NetSci 2023 Satellite Workshop"

timezone: Europe/Vienna

navigation:
  Home: "/2023/"
  Call for Papers: "/2023/cfp"
  Accepted Papers: "/2023/papers"
  Speakers: "/2023/speakers"
  Schedule: "/2023/schedule"
  Organizers: "/2023/organizers"
  Back: "https://netscisci.github.io/"

markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-seo-tag

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
